server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: cGlsb3RmaXJlcGxhY2V0ZWxscGh5c2ljYWxwb25ka25ld21pc3NpbmdvbGRlc3R0aHI=
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  image: images/

logging:
  level:
    org:
      springframework:
        security: DEBUG

# each restart a new password is generated to access the APIs so customize this setting
# == Moved to Database Basic Auth ==
# spring.security.user.name: pranesh
# spring.security.user.password: pranesh
# spring.security.user.roles: ADMIN
